# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e107e20acdf9ec1ac63c27629fa9720cc75ac5e3cd1167218ca2a9ddf5922c4c847f2a556fa9eca69d1292dd8ff01307328d1564adb1aff8b2f451c09891a58

test:
  secret_key_base: a2ab43057bb71c2e33c2a7a575a53a46114709c24deddf9201fb7d2b7441f9168d3b793bc2164004ab7f2f0e93a80be8074cde9fbf9df9a144c5c9cb12351a34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
